@api_HostAddress = https://localhost:5000/api

GET {{api_HostAddress}}/assignment
Accept: application/json

###

POST {{api_HostAddress}}/assignment

Answer:postanswer
Topic:postTopic
Subject:postsubject
Subtest:2
Level:C
Subquestion:postSubquestion
Points:10
Number:3

Images: @"./testImg/Sk%C3%A6rmbillede%202026-03-04%20083548.png"
Images: @"./testImg/Sk%C3%A6rmbillede%202026-03-04%20083714.png"
###

GET {{api_HostAddress}}/video
Accept: application/json

###

