@api_HostAddress = http://localhost:5000

GET {{api_HostAddress}}/api/assignment
Accept: application/json

###

POST {{api_HostAddress}}/api/assignment

Answer:postanswer
Topic:postTopic
Subject:postsubject
Subtest:2
Level:C
Subquestion:postSubquestion
Points:10
Number:3

Images: @"./testImg/Sk%C3%A6rmbillede%202026-03-04%20083548.png"
Images: @"./testImg/Sk%C3%A6rmbillede%202026-03-04%20083714.png"
###
